#!/usr/bin/env zsh
# Check if script exists in package.json
is_script_in_package_json() {
  node -e "try {
    const pkg = require('./package.json');
    console.log(pkg.scripts && pkg.scripts['$1'] ? 'true' : 'false');
  } catch (error) {
    throw new Error('Error:', error);
  }"
}
