#!/usr/bin/env zsh
# List available npm/yarn scripts
list_scripts_in_package_json() {
  node -e "try {
    const pkg = require('./package.json');
    console.log(Object.keys(pkg.scripts || {}).join('\n'));
  } catch (error) {
    console.error('Failed to read scripts from package.json:', error.message);
    process.exit(1);
  }"
}
